import type { Metadata } from "next";
import { Afacad_Flux } from "next/font/google";
import "./globals.css";
import { getGeneralLayout } from "@/lib/hygraph";
import Footer from "@/components/Footer";
import Header from "@/components/Header";

const afacadFlux = Afacad_Flux({
  variable: "--font-afacad-flux",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const generalLayout = await getGeneralLayout();
  return (
    <>
      <Header navigationLinks={generalLayout.headerMenu.navigationLinks} />
      <html lang="en" className={`${afacadFlux.variable} h-full`}>
        <body className="min-h-full flex flex-col">{children}</body>
      </html>
      <Footer
        title={generalLayout.footerMenu.title}
        navigationLinks={generalLayout.footerMenu.navigationLinks}
      />
    </>
  );
}
